filename=['output/1.mp4'];
out=VideoWriter(filename);
out.FrameRate=10;
open(out);
n = length(two_res3.t);
res = two_res3;
ne = 75;
ni = 25;
for i =1:n
    V_e = res.V_e(1,ne*(i-1)+1: ne*i);
    H_ee = res.H_ee(1,ne*(i-1)+1: ne*i);
    V_i = res.V_i(1,ni*(i-1)+1: ni*i);
    H_ie = res.H_ie(1,ni*(i-1)+1: ni*i);
    H_ee_G = H_ee(V_e == 1);
    H_ee_B = H_ee(V_e == 0);
    H_ie_G = H_ie(V_i == 1);
    H_ie_B = H_ie(V_i == 0);
    subplot(2,2,1);
    histogram(H_ee_G);
    ylim([0, 75]);
    xlim([0, 10]);
    title('H_{EEG}');
    subplot(2,2,2);
    histogram(H_ee_B);
    ylim([0, 75]);
    xlim([0, 10]);
    title('H_{EEB}');
    subplot(2,2,3);
    histogram(H_ie_G);
    ylim([0, 25]);
    xlim([0, 15]);
    title('H_{IEG}');
    subplot(2,2,4);
    histogram(H_ie_B);
    ylim([0, 25]);
    xlim([0, 15]);
    title('H_{IEB}');
    set(gcf,'Position',[10,10,1000,1000]);
    F=getframe(gcf);
    writeVideo(out,F);
end